# Generated by Django 4.1.5 on 2023-01-18 22:44

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='identifier',
            field=models.CharField(default=chat.models.idgen, max_length=30),
        ),
    ]
