# Generated by Django 4.1.5 on 2023-01-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
