# Generated by Django 4.1.5 on 2023-01-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='identifier',
            new_name='uuid',
        ),
    ]
