# Generated by Django 4.1.5 on 2023-01-23 04:58

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_identifier_room_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default=chat.models.name_gen, max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(blank=True, max_length=30, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
        ),
    ]
