# Generated by Django 4.1.5 on 2023-01-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_talker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talker',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
